export default {
    GET_PORTALS_ATTEMPTED: "GET_PORTALS_ATTEMPTED",
    GET_PORTALS_REJECTED: "GET_PORTALS_REJECTED",
    GET_PORTALS_SUCCEEDED: "GET_PORTALS_SUCCEEDED",
    ADD_PORTAL_ATTEMPTED: "ADD_PORTAL_ATTEMPTED",
    ADD_PORTAL_REJECTED: "ADD_PORTAL_REJECTED",
    ADD_PORTAL_SUCCEEDED: "ADD_PORTAL_SUCCEEDED",
    UPDATE_PORTAL_ATTEMPTED: "UPDATE_PORTAL_ATTEMPTED",
    UPDATE_PORTAL_REJECTED: "UPDATE_PORTAL_REJECTED",
    UPDATE_PORTAL_SUCCEEDED: "UPDATE_PORTAL_SUCCEEDED",
    DELETE_PORTAL_ATTEMPTED: "DELETE_PORTAL_ATTEMPTED",
    DELETE_PORTAL_REJECTED: "DELETE_PORTAL_REJECTED",
    DELETE_PORTAL_SUCCEEDED: "DELETE_PORTAL_SUCCEEDED",
}