export default {
    LOGIN_ATTEMPTED: "LOGIN_ATTEMPTED",
    LOGIN_ACCEPTED: "LOGIN_ACCEPTED",
    LOGIN_REJECTED: "LOGIN_REJECTED",
    LOGOUT_ATTEMPTED: "LOGOUT_ATTEMPTED",
    LOGOUT_SUCCESSFUL: "LOGOUT_SUCCESSFUL",
    AUTHORIZE_ATTEMPTED: "AUTHORIZE_ATTEMPTED",
    AUTHORIZE_ACCEPTED: "AUTHORIZE_ACCEPTED",
    AUTHORIZE_REJECTED: "AUTHORIZE_REJECTED",
}