export default {
    GET_PORTALTYPES_ATTEMPTED: "GET_PORTALTYPES_ATTEMPTED",
    GET_PORTALTYPES_REJECTED: "GET_PORTALTYPES_REJECTED",
    GET_PORTALTYPES_SUCCEEDED: "GET_PORTALTYPES_SUCCEEDED",
    ADD_PORTALTYPE_ATTEMPTED: "ADD_PORTALTYPE_ATTEMPTED",
    ADD_PORTALTYPE_REJECTED: "ADD_PORTALTYPE_REJECTED",
    ADD_PORTALTYPE_SUCCEEDED: "ADD_PORTALTYPE_SUCCEEDED",
    UPDATE_PORTALTYPE_ATTEMPTED: "UPDATE_PORTALTYPE_ATTEMPTED",
    UPDATE_PORTALTYPE_REJECTED: "UPDATE_PORTALTYPE_REJECTED",
    UPDATE_PORTALTYPE_SUCCEEDED: "UPDATE_PORTALTYPE_SUCCEEDED",
    DELETE_PORTALTYPE_ATTEMPTED: "DELETE_PORTALTYPE_ATTEMPTED",
    DELETE_PORTALTYPE_REJECTED: "DELETE_PORTALTYPE_REJECTED",
    DELETE_PORTALTYPE_SUCCEEDED: "DELETE_PORTALTYPE_SUCCEEDED",
}