export default {
    GET_USERS_ATTEMPTED: "GET_USERS_ATTEMPTED",
    GET_USERS_REJECTED: "GET_USERS_REJECTED",
    GET_USERS_SUCCEEDED: "GET_USERS_SUCCEEDED",
    ADD_USER_ATTEMPTED: "ADD_USER_ATTEMPTED",
    ADD_USER_REJECTED: "ADD_USER_REJECTED",
    ADD_USER_SUCCEEDED: "ADD_USER_SUCCEEDED",
    UPDATE_USER_ATTEMPTED: "UPDATE_USER_ATTEMPTED",
    UPDATE_USER_REJECTED: "UPDATE_USER_REJECTED",
    UPDATE_USER_SUCCEEDED: "UPDATE_USER_SUCCEEDED",
    DELETE_USER_ATTEMPTED: "DELETE_USER_ATTEMPTED",
    DELETE_USER_REJECTED: "DELETE_USER_REJECTED",
    DELETE_USER_SUCCEEDED: "DELETE_USER_SUCCEEDED",
}