export default {
    GET_ITEMS_ATTEMPTED: "GET_ITEMS_ATTEMPTED",
    GET_ITEMS_REJECTED: "GET_ITEMS_REJECTED",
    GET_ITEMS_SUCCEEDED: "GET_ITEMS_SUCCEEDED",
    ADD_ITEM_ATTEMPTED: "ADD_ITEM_ATTEMPTED",
    ADD_ITEM_REJECTED: "ADD_ITEM_REJECTED",
    ADD_ITEM_SUCCEEDED: "ADD_ITEM_SUCCEEDED",
    UPDATE_ITEM_ATTEMPTED: "UPDATE_ITEM_ATTEMPTED",
    UPDATE_ITEM_REJECTED: "UPDATE_ITEM_REJECTED",
    UPDATE_ITEM_SUCCEEDED: "UPDATE_ITEM_SUCCEEDED",
    DELETE_ITEM_ATTEMPTED: "DELETE_ITEM_ATTEMPTED",
    DELETE_ITEM_REJECTED: "DELETE_ITEM_REJECTED",
    DELETE_ITEM_SUCCEEDED: "DELETE_ITEM_SUCCEEDED",
}