export default {
    GET_FEEDS_ATTEMPTED: "GET_FEEDS_ATTEMPTED",
    GET_FEEDS_REJECTED: "GET_FEEDS_REJECTED",
    GET_FEEDS_SUCCEEDED: "GET_FEEDS_SUCCEEDED",
    ADD_FEED_ATTEMPTED: "ADD_FEED_ATTEMPTED",
    ADD_FEED_REJECTED: "ADD_FEED_REJECTED",
    ADD_FEED_SUCCEEDED: "ADD_FEED_SUCCEEDED",
    UPDATE_FEED_ATTEMPTED: "UPDATE_FEED_ATTEMPTED",
    UPDATE_FEED_REJECTED: "UPDATE_FEED_REJECTED",
    UPDATE_FEED_SUCCEEDED: "UPDATE_FEED_SUCCEEDED",
    DELETE_FEED_ATTEMPTED: "DELETE_FEED_ATTEMPTED",
    DELETE_FEED_REJECTED: "DELETE_FEED_REJECTED",
    DELETE_FEED_SUCCEEDED: "DELETE_FEED_SUCCEEDED",
}