export default {
    GET_TRANSITIONTYPES_ATTEMPTED: "GET_TRANSITIONTYPES_ATTEMPTED",
    GET_TRANSITIONTYPES_REJECTED: "GET_TRANSITIONTYPES_REJECTED",
    GET_TRANSITIONTYPES_SUCCEEDED: "GET_TRANSITIONTYPES_SUCCEEDED",
    ADD_TRANSITIONTYPE_ATTEMPTED: "ADD_TRANSITIONTYPE_ATTEMPTED",
    ADD_TRANSITIONTYPE_REJECTED: "ADD_TRANSITIONTYPE_REJECTED",
    ADD_TRANSITIONTYPE_SUCCEEDED: "ADD_TRANSITIONTYPE_SUCCEEDED",
    UPDATE_TRANSITIONTYPE_ATTEMPTED: "UPDATE_TRANSITIONTYPE_ATTEMPTED",
    UPDATE_TRANSITIONTYPE_REJECTED: "UPDATE_TRANSITIONTYPE_REJECTED",
    UPDATE_TRANSITIONTYPE_SUCCEEDED: "UPDATE_TRANSITIONTYPE_SUCCEEDED",
    DELETE_TRANSITIONTYPE_ATTEMPTED: "DELETE_TRANSITIONTYPE_ATTEMPTED",
    DELETE_TRANSITIONTYPE_REJECTED: "DELETE_TRANSITIONTYPE_REJECTED",
    DELETE_TRANSITIONTYPE_SUCCEEDED: "DELETE_TRANSITIONTYPE_SUCCEEDED",
}